const iphone17Pro256 = [
{
  _id: "69ea542847825c3bcd5b78d2",
  name: "أبل آيفون 17 برو، 5G، 6.1 بوصة، سيلفر، 256 جيجا",
  originalPrice: 5500,
  salePrice: 4480,
  description: "الشروط الواجب توفرها للتقديم:\r\n\r\n• مواطن سعودي او مقيم بإقامة سارية.\r\n• اتمام سداد الدفعة المقدمة لتأكيد الطلب.\r\n• تقديم بيانات صحيحة للتواصل والمتابعة.\r\n• توقيع عقد الأقساط عند استلام الجهاز.\r\n• الالتزام بسداد القسط الشهري في موعده.",
  image: "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776083416/products/ldxuglcctmhjska5gnnw.webp",
  images: [
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776083416/products/ldxuglcctmhjska5gnnw.webp",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811543/iPhone_17_Pro_Max_Silver_PDP_Image_Position_2__en-ME-scaled_m3f9kk.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811544/iPhone_17_Pro_Max_Silver_PDP_Image_Position_4__en-ME-scaled_ggtpon.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811565/iPhone_17_Pro_Max_Silver_PDP_Image_Position_3__en-ME-scaled_g67rs7.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811544/iPhone_17_Pro_Max_Silver_PDP_Image_Position_8__en-ME-scaled_hdnbnl.avif",
  ],
  color: "سيلفر",
  storage: "256 GB",
  network: "5G",
  screenSize: "6.1 بوصة",
  category: "ابل ايفون 17 برو",
  subCategory: "الهواتف الذكية",
  brand: "Apple",
  inStock: true,
  freeDelivery: true,
  deliveryTime: "24 ساعة",
  warrantyYears: 2,
  taxIncluded: true,

  overview: `التصميم المبتكر لآيفون 17 برو يوفر متانة استثنائية، وعمر بطارية مذهل، ويقدم القوة الاستثنائية لشريحة A19 Pro.
نظام كاميرا Pro Fusion بدقة 48 ميجابكسل يحتوي على أطول عدسة تليفوتو في تاريخ آيفون مع زوم 8x، وكاميرا أمامية Center Stage لصور سيلفي جماعية أذكى وفيديو مزدوج الالتقاط.
درع السيراميك 2 في الأمام يوفر مقاومة للخدوش أفضل بمقدار 3 مرات، وهيكل من الألمنيوم المصنوع بالطرق لتبديد الحرارة.
يدعم أدوات ذكاء آبل المفيدة مثل التنظيف والمزيد.`,

  features: {
    screenAndDesign: [
      "شاشة Super Retina XDR",
      "تقنية ProMotion",
      "شاشة دائمة التشغيل (Always-On)",
      "الجزيرة الديناميكية (Dynamic Island)",
      "هيكل أحادي من الألمنيوم (Aluminum Unibody)",
      "زر الإجراءات (Action Button)",
      "التحكم في الكاميرا للوصول السريع لأدوات الصور والفيديو",
    ],
    performance: [
      "شريحة A19 Pro",
      "معالج رسومي سداسي النواة مع مسرّعات عصبية",
      "تتبع الأشعة المدعوم عتاديًا",
    ],
    battery: [
      "يصل إلى 39 ساعة من تشغيل الفيديو"
    ],
    frontCamera: [
      "كاميرا أمامية 18 ميجابكسل مع Center Stage",
      "النقر للتكبير والتدوير",
      "Center Stage للصور",
      "فيديو ثابت للغاية",
      "التقاط مزدوج",
      "Center Stage لمكالمات الفيديو",
    ],
    rearCamera: [
      "نظام كاميرا Pro Fusion بدقة 48 ميجابكسل",
      "48 ميجابكسل رئيسية",
      "48 ميجابكسل واسعة جدًا",
      "48 ميجابكسل تليفوتو",
      "صور فائقة الدقة (24 و 48 ميجابكسل)",
      "بورتريه الجيل الجديد مع التحكم في العمق والتركيز",
      "تصوير ماكرو",
    ],
    videoAndPhotography: [
      "Dolby Vision حتى 4K بمعدل 120 إطار/ثانية",
      "أنماط تصوير فوتوغرافي من الجيل الأحدث",
    ],
  },

  detailedSpecs: {
    memoryType: "بدون ذاكرة قابلة للزيادة",
    simCount: "مزدوج الشريحة",
    ram: "12 GB",
    internalStorage: "256 GB",
    edition: "نسخة الشرق الأوسط (eSIM)",
    colorName: "سيلفر",
    os: "iOS",
    processorName: "أبل",
    mainCameraFeature: "ثلاثية",
    audioJack: "نوع C",
    voiceDialing: "نعم",
    fastCharging: "نعم",
    modelName: "iPhone 17 Pro",
    secondaryCameraResolution: "18 MP",
    secondaryCameraRange: "16 - 31.9 ميجابكسل",
    batterySize: "4252 mAh",
    screenSize: "6.3 بوصة",
    simType: "شريحة إلكترونية",
    chargingType: "نوع C",
    condition: "جديد",
    coreCount: "سداسي النواة",
    flash: "فلاش مزدوج",
    networkType: "تقنية 5G",
    processorNumber: "Apple A19 Pro",
    modelNumber: "MG864AH/A",
    mainCamera: "48 + 48 + 48 ميجابكسل",
  },
}
,

  {
  _id: "69ea542847825c3bcd5b78da",
  name: "أبل آيفون 17 برو، 5G، 6.1 بوصة، برتقالي، 256 جيجا",
  originalPrice: 5500,
  salePrice: 4480,
  description: "الشروط الواجب توفرها للتقديم:\r\n\r\n• مواطن سعودي او مقيم بإقامة سارية.\r\n• اتمام سداد الدفعة المقدمة لتأكيد الطلب.\r\n• تقديم بيانات صحيحة للتواصل والمتابعة.\r\n• توقيع عقد الأقساط عند استلام الجهاز.\r\n• الالتزام بسداد القسط الشهري في موعده.",
  image: "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1777152960/products/cg4hm4876ipi0jo8qyij.jpg",
  images: [
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1777152960/products/cg4hm4876ipi0jo8qyij.jpg",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776809665/iPhone_17_Pro_Max_Cosmic_Orange_PDP_Image_Position_2__en-ME-scaled_cq8adp.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776809850/iPhone_17_Pro_Max_Cosmic_Orange_PDP_Image_Position_3__en-ME-scaled_virgnn.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776809851/iPhone_17_Pro_Max_Cosmic_Orange_PDP_Image_Position_4__en-ME-scaled_rlbvtw.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776809851/iPhone_17_Pro_Max_Cosmic_Orange_PDP_Image_Position_8__en-ME-scaled_rvlkmo.avif",
  ],
  color: "برتقالي",
  storage: "256 GB",
  network: "5G",
  screenSize: "6.1 بوصة",
  category: "ابل ايفون 17 برو",
  subCategory: "الهواتف الذكية",
  brand: "Apple",
  inStock: true,
  freeDelivery: true,
  deliveryTime: "24 ساعة",
  warrantyYears: 2,
  taxIncluded: true,

  overview: `التصميم المبتكر لآيفون 17 برو يوفر متانة استثنائية، وعمر بطارية مذهل، ويقدم القوة الاستثنائية لشريحة A19 Pro.
نظام كاميرا Pro Fusion بدقة 48 ميجابكسل يحتوي على أطول عدسة تليفوتو في تاريخ آيفون مع زوم 8x، وكاميرا أمامية Center Stage لصور سيلفي جماعية أذكى وفيديو مزدوج الالتقاط.
درع السيراميك 2 في الأمام يوفر مقاومة للخدوش أفضل بمقدار 3 مرات، وهيكل من الألمنيوم المصنوع بالطرق لتبديد الحرارة.
يدعم أدوات ذكاء آبل المفيدة مثل التنظيف والمزيد.`,

  features: {
    screenAndDesign: [
      "شاشة Super Retina XDR",
      "تقنية ProMotion",
      "شاشة دائمة التشغيل",
      "الجزيرة الديناميكية",
      "هيكل ألمنيوم أحادي",
      "زر الإجراءات",
      "التحكم السريع بالكاميرا",
    ],
    performance: [
      "شريحة A19 Pro",
      "معالج رسومي سداسي النواة مع مسرّعات عصبية",
      "تتبع الأشعة المدعوم عتاديًا",
    ],
    battery: ["يصل إلى 39 ساعة تشغيل فيديو"],
    frontCamera: [
      "كاميرا أمامية 18 ميجابكسل مع Center Stage",
      "تكبير وتدوير بالنقر",
      "فيديو ثابت للغاية",
      "التقاط مزدوج",
    ],
    rearCamera: [
      "نظام كاميرا Pro Fusion 48 ميجابكسل",
      "عدسة رئيسية 48MP",
      "عدسة واسعة جدًا 48MP",
      "عدسة تليفوتو 48MP",
      "صور فائقة الدقة",
      "تصوير بورتريه متطور",
      "ماكرو",
    ],
    videoAndPhotography: [
      "تصوير Dolby Vision حتى 4K 120fps",
      "أنماط تصوير حديثة",
    ],
  },

  detailedSpecs: {
    memoryType: "بدون ذاكرة قابلة للزيادة",
    simCount: "مزدوج الشريحة",
    ram: "12 GB",
    internalStorage: "256 GB",
    edition: "نسخة الشرق الأوسط (eSIM)",
    colorName: "Cosmic Orange",
    os: "iOS",
    processorName: "أبل",
    mainCameraFeature: "ثلاثية",
    audioJack: "نوع C",
    voiceDialing: "نعم",
    fastCharging: "نعم",
    modelName: "iPhone 17 Pro",
    secondaryCameraResolution: "18 MP",
    secondaryCameraRange: "16 - 31.9 ميجابكسل",
    batterySize: "4252 mAh",
    screenSize: "6.3 بوصة",
    simType: "شريحة إلكترونية",
    chargingType: "نوع C",
    condition: "جديد",
    coreCount: "سداسي النواة",
    flash: "فلاش مزدوج",
    networkType: "5G",
    processorNumber: "Apple A19 Pro",
    modelNumber: "MG864AH/A",
    mainCamera: "48 + 48 + 48 ميجابكسل",
  },
},



{
  _id: "69ea542847825c3bcd5b78e2",
  name: "أبل آيفون 17 برو، 5G، 6.1 بوصة، أزرق، 256 جيجا",
  originalPrice: 5500,
  salePrice: 4480,
  description: "الشروط الواجب توفرها للتقديم:\r\n\r\n• مواطن سعودي او مقيم بإقامة سارية.\r\n• اتمام سداد الدفعة المقدمة لتأكيد الطلب.\r\n• تقديم بيانات صحيحة للتواصل والمتابعة.\r\n• توقيع عقد الأقساط عند استلام الجهاز.\r\n• الالتزام بسداد القسط الشهري في موعده.",
  image: "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811286/Apple-IPhone-17-Pro-Max-With-FaceTime-256GB-12GB-RAM-_6069_1_txizyx.webp",
  images: [
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811286/Apple-IPhone-17-Pro-Max-With-FaceTime-256GB-12GB-RAM-_6069_1_txizyx.webp",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811230/iPhone_17_Pro_Max_Deep_Blue_PDP_Image_Position_2__en-ME-scaled_joodfj.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811231/iPhone_17_Pro_Max_Deep_Blue_PDP_Image_Position_4__en-ME-scaled_pdxb4b.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811231/iPhone_17_Pro_Max_Deep_Blue_PDP_Image_Position_3__en-ME-scaled_kdukwx.avif",
    "https://res.cloudinary.com/dyqkhcuxe/image/upload/v1776811232/iPhone_17_Pro_Max_Deep_Blue_PDP_Image_Position_8__en-ME-scaled_gozz08.avif",
  ],
  color: "أزرق",
  storage: "256 GB",
  network: "5G",
  screenSize: "6.1 بوصة",
  category: "ابل ايفون 17 برو",
  subCategory: "الهواتف الذكية",
  brand: "Apple",
  inStock: true,
  freeDelivery: true,
  deliveryTime: "24 ساعة",
  warrantyYears: 2,
  taxIncluded: true,

  overview: `التصميم المبتكر لآيفون 17 برو يوفر متانة استثنائية، وعمر بطارية مذهل، ويقدم القوة الاستثنائية لشريحة A19 Pro.
نظام كاميرا Pro Fusion بدقة 48 ميجابكسل مع زوم 8x، وكاميرا أمامية Center Stage لصور سيلفي أفضل.
درع السيراميك 2 لمقاومة الخدوش، وهيكل ألمنيوم لتبديد الحرارة.`,

  features: {
    screenAndDesign: [
      "شاشة Super Retina XDR",
      "تقنية ProMotion",
      "Always-On",
      "Dynamic Island",
    ],
    performance: [
      "A19 Pro",
      "GPU سداسي النواة",
    ],
    battery: ["حتى 39 ساعة فيديو"],
    frontCamera: ["18MP + Center Stage"],
    rearCamera: ["48MP ثلاثية"],
    videoAndPhotography: ["4K Dolby Vision"],
  },

  detailedSpecs: {
    memoryType: "بدون ذاكرة قابلة للزيادة",
    simCount: "مزدوج الشريحة",
    ram: "12 GB",
    internalStorage: "256 GB",
    edition: "نسخة الشرق الأوسط",
    colorName: "Deep Blue",
    os: "iOS",
    processorName: "أبل",
    mainCameraFeature: "ثلاثية",
    audioJack: "نوع C",
    voiceDialing: "نعم",
    fastCharging: "نعم",
    modelName: "iPhone 17 Pro",
    batterySize: "4252 mAh",
    networkType: "5G",
    mainCamera: "48 + 48 + 48",
  },
}
];